name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare deployment
        run: |
          mkdir -p build
          shopt -s extglob
          cp -r !(build|.git|.github) build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Diretório temporário onde os arquivos serão copiados
